// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyFMhIzqtc4kgHK5KRqvm25mOY6IKo5lA',
    appId: '1:373710538733:web:a44dfe05d1cd09c91889e4',
    messagingSenderId: '373710538733',
    projectId: 'sumnation-mobile',
    authDomain: 'sumnation-mobile.firebaseapp.com',
    storageBucket: 'sumnation-mobile.appspot.com',
    measurementId: 'G-TG9TG279CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaB2reugVFLE8NWUCEcL92TduT5hQYJM4',
    appId: '1:373710538733:android:04ae6eb07a93dd2c1889e4',
    messagingSenderId: '373710538733',
    projectId: 'sumnation-mobile',
    storageBucket: 'sumnation-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk9fpaJIXqkLLuNhdO8Fd0ju9F555rT5Y',
    appId: '1:373710538733:ios:72ee34e8190c4c531889e4',
    messagingSenderId: '373710538733',
    projectId: 'sumnation-mobile',
    storageBucket: 'sumnation-mobile.appspot.com',
    iosClientId: '373710538733-f5qqkhv6i0afpvjg7i4en94d8riis4t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk9fpaJIXqkLLuNhdO8Fd0ju9F555rT5Y',
    appId: '1:373710538733:ios:72ee34e8190c4c531889e4',
    messagingSenderId: '373710538733',
    projectId: 'sumnation-mobile',
    storageBucket: 'sumnation-mobile.appspot.com',
    iosClientId: '373710538733-f5qqkhv6i0afpvjg7i4en94d8riis4t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
